### ISSUE TITLE
When running the pedestrians cue to estimate the illumination

### ISSUE THREAD

**Issue by crun840130** [jflalonde/illuminationSingleImage#2]
Hi jflalonde ,I got a problem when using the cue of pedestrians, the dimension of the HOG feature doesn't match with the dimension of the minVal and scale from the model lightingGivenObjectClassifier. 
How to solve this problem?

**Comment by crun840130** [comment]
the error was like this
Matrix dimensions must agree.

Error in scaleFeaturesSVM (line 16)
scaledFeats = (feats - repmat(minVal,size(feats,1),1))*scale;

Error in applyLocalClassifier (line 53)
    featsScaled = scaleFeaturesSVM(feats, classifInfo.minVal, classifInfo.scale);

Error in computePedestrianProbabilities (line 36)
    pLocalLightingGivenObject(i_obj,:) = applyLocalClassifier(lightingFeatures, ...

Error in estimateIllumination (line 118)
        pLocalLightingGivenNonObject] = computePedestrianProbabilities(img, ...

Error in demoEstimateIllumination (line 148)
    estimateIllumination(img, focalLength, horizonLine, ...

**Comment by jflalonde** [comment]
Sorry, I can't provide support for the code anymore. If you find the solution, feel free to ask for a pull request!
